### PR TITLE
Migrate to gtk 0.13.*

### PR DESCRIPTION
**Pull request by YoEight**
1. Add support to Stackage LTS: Stackage LTS is a curated list of well behaving packages. Any package listed guarantees to not get you in a cabal hell situation. I didn't enable package retrieving from Stackage server though, because we use couple of packages not approved yet (`recursion-schemes` and `poppler`) 

2. Code migration to `gtk 0.13.*`: That new version breaks a lot of things, fortunately in a good way: Major point is support to `text` package instead of `String` for storing textual data. That leads for better memory usage and probably some performance boost for code relying a lot on text transformations.

With that patch, we gain much more stability regarding cabal compilation, as we now relying on fixed set of packages. 

I only test that on Linux (up-to-date ArchLinux system)

### CODE REVIEW

**Comment by YoEight** [comment]
Assigned @cchantep

**Comment by cchantep** [comment]
Will try on other platform.

Could you squash commits meanwhile?

**Comment by cchantep** [comment]
Thanks @YoEight . Working fine on Yosemite. Will try build on Win/Mountain Lion.

**Comment by cchantep** [comment]
@YoEight Mac OS X build is working fine on both Yosemite and Mountain Lion

**Pull request merged**
